# ------------------------------------------------------------------------------
# appVeyor script
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

version: 0.0.{build}

image: Visual Studio 2019
configuration: Release
platform: x64

clone_depth: 1
clone_folder: c:\build\vrprouting

cache:
  - downloads -> appveyor.yml
  - c:\build\local\msvc160\x64 -> appveyor

services:
  - postgresql101

environment:
  CONFIGURATION: Release
  MSVC_VER: 16.0
  BUILD_ROOT_DIR: c:\build
  PGIS_VERSION: 3.2
  PG_VER: 10


init:
  - git config --global core.autocrlf false

install:
  # Install pgRouting prerequisites:
  # cmake
  # postGIS
  - call ci\appveyor\install.bat


build_script:
  - cd c:\build\vrprouting\ci\appveyor
  - msbuild_pgrouting.bat %PG_VER%
  - cd %PGROUTING_BUILD_DIR%
  - msbuild PGROUTING.sln /target:Build /property:Configuration=%CONFIGURATION%
  - msbuild INSTALL.vcxproj /target:Build /property:Configuration=%CONFIGURATION%

test_script:
  - set PGUSER=postgres
  - set PGPASSWORD=Password12!
  - set PGHOME=C:\Progra~1\PostgreSQL\%PG_VER%
  - set PGPORT=5432
  - set PATH=%PATH%;%PGHOME%\bin
  # Execute algorithm test by Cygwin
  #- C:\cygwin\bin\bash -lc "cd /cygdrive/c/build/pgrouting && tools/testers/doc_queries_generator.pl -psql \"/cygdrive/c/Progra~1/PostgreSQL/%PG_VER%/bin/psql\""
