#----------------------
# Configuration file for compilation
#
#  Once in the file, do not change the order
#
# Directory         | has C/C++ | has SQL | has DOC
#----------------------
#----------------------
# common must be first can not be removed
#----------------------
pg_controls         | N | Y | N
common              | Y | N | N
cpp_common          | Y | N | N
#----------------------
# SQL file is build in order presented in this file
# Dependencies must be considered when adding a line
#----------------------
version             | Y | Y | Y

# used by pgr_pickDeliver
problem             | Y | N | N
optimizers          | Y | N | N
initialsol          | Y | N | N

pgr_pickDeliver     | Y | Y | Y

utilities           | N | N | N
compatibleVehicles  | N | N | N
pickDeliver         | N | N | N
pickDeliverAdd      | N | N | N
optimize            | N | N | N
viewRoute           | N | N | N
simulation          | N | N | N
vroom               | N | N | N
or_tools            | N | N | N
