name: Build for macOS

on:
  push:
    branches-ignore:
      - 'translations_*'
    tags: []
  pull_request:
    paths-ignore:
      - '**.po'

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install deps
        run: |
          brew install postgis boost pgrouting
          brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/3c66798c39fdb6a7c8b15630035125cac63c3fa2/Formula/pgtap.rb

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DWITH_DOC=OFF ..

      - name: Build
        run: |
          cd build
          make -j
          sudo make install

      - name: Test
        run: |
          export PATH=/usr/local/Cellar/perl/$(perl -e 'print substr($^V, 1)')/bin:$PATH
          pg_ctl -D /usr/local/var/postgres start
          createuser -s postgres
          createdb ___vrp___test___
          bash ./tools/testers/pg_prove_tests.sh postgres 5432 Release
