name: Build for macOS

on:
  push:
    branches-ignore:
      - 'translations_*'
    tags: []
  pull_request:
    paths-ignore:
      - '**.po'

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache pgtap
        id: cache-pgtap
        uses: actions/cache@v2
        with:
          path: ./pgTapExtension/
          key: ${{ runner.os }}-pgtap-${{ hashFiles('**/packages*.txt') }}

      - name: Get pgtap repo
        if: steps.cache-pgtap.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: theory/pgtap
          path: ./pgTapExtension/

      - name: Install pgTAP
        if: steps.cache-pgtap.outputs.cache-hit != 'true'
        run: |
          cd ./pgTapExtension/
          make -j
          sudo make install
          cpan TAP::Parser::SourceHandler::pgTAP

      - name: Install pgTAP
        if: steps.cache-pgtap.outputs.cache-hit == 'true'
        run: |
          cd ./pgTapExtension/
          sudo make install
          cpan TAP::Parser::SourceHandler::pgTAP

      - name: install deps
        run: |
          brew install postgis boost pgrouting

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DWITH_DOC=OFF ..

      - name: Build
        run: |
          cd build
          make -j
          sudo make install

      - name: Test
        run: |
          export PATH=/usr/local/Cellar/perl/$(perl -e 'print substr($^V, 1)')/bin:$PATH
          pg_ctl -D /usr/local/var/postgres start
          createuser -s postgres
          createdb ___vrp___test___
          bash ./tools/testers/pg_prove_tests.sh postgres 5432 Release
