name: Build for macOS

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/macos.yml'

    branches-ignore:
      - 'gh-pages'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

# TODO: Fix the macOS build for compiling and building VROOM with vrprouting.
jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          brew install postgis boost pgrouting openssl asio glpk


      - name: Cache VROOM
        id: cache-vroom
        uses: actions/cache@v4
        env:
          cache-name: vroom
        with:
          path: |
            ~/vroom-${{ env.VROOMVER }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.VROOMVER }}

      - name: Build VROOM
        if: steps.cache-vroom.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/VROOM-Project/vroom/archive/refs/tags/v1.12.0.tar.gz
          tar -zxf v1.12.0.tar.gz
          cd vroom-1.12.0/src

          echo 'here 1'

          # Source: https://github.com/VROOM-Project/vroom/issues/378
          sudo ln -s /usr/local/opt/openssl/include/openssl /usr/local/include
          sudo ls /usr/local
          echo 'here 2'
          sudo ln -s /usr/local/opt/openssl/lib/libssl.dylib /usr/local/lib/
          sudo ln -s /usr/local/opt/openssl/lib/libcrypto.dylib /usr/local/lib/
          echo 'here3'

          # Create object file with position independent code using -fPIC flag
          sed -i '' -e 's/CXXFLAGS = /CXXFLAGS = -fPIC /' makefile
          echo 'here4'
          sed -i '' -e 's/\/usr\/include\/glpk.h/\/usr\/local\/opt\/glpk\/include\/glpk.h/' makefile
          echo 'here5'

          make
          echo 'here6'
          cd ..
          echo "VROOM_INSTALL_PATH=$(pwd)" >> $GITHUB_ENV

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DWITH_DOC=OFF -DVROOM_INSTALL_PATH=${VROOM_INSTALL_PATH} ..

      - name: Build
        run: |
          cd build
          make -j 4
          sudo make install

      - name: Cache pgtap
        id: cache-pgtap
        uses: actions/cache@v4
        with:
          path: ./pgTapExtension/
          key: ${{ runner.os }}-pgtap-${{ hashFiles('**/packages*.txt') }}

      - name: Get pgtap repo
        if: steps.cache-pgtap.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: theory/pgtap
          path: ./pgTapExtension/

      - name: Install pgTAP
        if: steps.cache-pgtap.outputs.cache-hit != 'true'
        run: |
          cd ./pgTapExtension/
          make -j
          sudo make install
          cpan TAP::Parser::SourceHandler::pgTAP

      - name: Install pgTAP
        if: steps.cache-pgtap.outputs.cache-hit == 'true'
        run: |
          cd ./pgTapExtension/
          sudo make install
          cpan TAP::Parser::SourceHandler::pgTAP

      - name: Unpack data
        run: |
          cd tools/testers
          tar -xf matrix_new_values.tar.gz

      - name: Create superuser
        run: |
          export PATH=/usr/local/Cellar/perl/$(perl -e 'print substr($^V, 1)')/bin:$PATH
          pg_ctl -D /usr/local/var/postgres start
          export PG_RUNNER_USER=`whoami`
          sudo -u postgres psql -p ${PGPORT} -c "DROP DATABASE IF EXISTS \"${PG_RUNNER_USER}\";"
          sudo -u postgres psql -p ${PGPORT} -c "DROP ROLE IF EXISTS \"${PG_RUNNER_USER}\";"
          sudo -u postgres psql -p ${PGPORT} -c "CREATE ROLE \"${PG_RUNNER_USER}\" WITH LOGIN SUPERUSER;"
          sudo -u postgres psql -p ${PGPORT} -c "CREATE DATABASE \"${PG_RUNNER_USER}\";"
          echo "PG_RUNNER_USER=${PG_RUNNER_USER}" >> $GITHUB_ENV

      - name: Test documentation queries are up to date
        run: |
          export PATH=/usr/local/Cellar/perl/$(perl -e 'print substr($^V, 1)')/bin:$PATH
          pg_ctl -D /usr/local/var/postgres start
          createuser -s postgres
          createdb ___vrp___test___
          cd tools/testers
          psql -p 5432 -U postgres -d ___vrp___test___ -X -q -v ON_ERROR_STOP=1 --pset pager=off -f setup_db.sql
          psql -p 5432 -U postgres -d ___vrp___test___ -c "SELECT * FROM pgr_full_version();"
          pg_prove --failures --quiet --recurse --ext .sql -p 5432 -d ___vrp___test___ -U postgres ../../pgtap/
