name: Website

on:
  workflow_dispatch:

env:
    release: Release
    os: ubuntu-latest

permissions:
  contents: write

jobs:
  update-website:
    name: Update Website
    runs-on: ubuntu-latest
    # disbale action, we need a: pgorpy.pgrouting.org
    if: ${{ false }}
    #if: ${{ github.repository_owner == 'pgRouting' }}
    strategy:
        fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract branch name and commit hash
        run: |
          branch=${GITHUB_REF#refs/heads/}
          echo "BRANCH=$branch" >> $GITHUB_ENV
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "GIT_HASH=$git_hash" >> $GITHUB_ENV

      - name: Get postgres version
        run: |
          sudo service postgresql start
          PGVER=$(psql --version | grep -Po '(?<=psql \(PostgreSQL\) )[^;]+(?=\.\d+ \()')
          echo "PGVER=${PGVER}" >> $GITHUB_ENV
          echo "PGPORT=5432" >> $GITHUB_ENV

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update

          # Basic dependencies
          sudo apt-get install -y \
            postgresql-${PGVER} \
            postgresql-server-dev-${PGVER}

          # documentation dependencies
          sudo apt-get install -y \
            graphviz \
            python3-sphinx \
            python3-sphinx-bootstrap-theme

      - name: Install Google OR-Tools
        run: |
          sudo pip install --root=/ ortools==9.10.4067

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ env.release }} \
                -DDOC_USE_BOOTSTRAP=ON -DWITH_DOC=ON ..

      - name: Build
        run: |
          cd build
          make doc

      - name: Initialize mandatory git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update Users Documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ env.BRANCH }}" == "main" ]]; then
            FOLDER_NAME="main"
          elif [[ "${{ env.BRANCH }}" == "develop" ]]; then
            FOLDER_NAME="dev"
          fi
          git checkout origin/gh-pages
          git checkout -b gh-pages
          rm -rf ${FOLDER_NAME}
          cp -r build/doc/_build/html ${FOLDER_NAME}
          git add ${FOLDER_NAME}
          git diff-index --quiet HEAD || git commit -m "Update users documentation for ${PROJECT_VERSION} (${{ env.BRANCH }}): commit ${{ env.GIT_HASH }}"
          git fetch origin
          git rebase origin/gh-pages
          git push origin gh-pages
          git checkout @{-2}
